### ISSUE TITLE
Cannot use double quotes in queries. 

### ISSUE THREAD

**Issue by kxzhang** [datahuborg/datahub#121] opened 2016-03-10 18:41 UTC
Postgres does not allow the use of double quotes in queries to create text strings. We should update the error message displayed to users to inform them of this problem (currently the error message is very uninformative and just states "ProgrammingError").

**Comment by RogerTangos** [comment] 2016-03-10 18:57
+1. Likely will happen in using the REST api, since src/browser/views needs to be refactored anyhow.

**Comment by RogerTangos** [comment] 2016-06-01 18:05
Duplicate of #147

**Closed by RogerTangos** 2016-06-01 18:05 UTC
Labels: enhancement
