### ISSUE TITLE
www.datahub.csail.mit.edu's DNS is misconfigured

### ISSUE THREAD

**Issue by RogerTangos** [datahuborg/datahub#30] opened 2015-05-27 14:52 UTC
datahub.csail.mit.edu <-- works
www.datahub.csail.mit.edu <-- doesn't work

**Comment by justinanderson** [comment] 2016-04-07 14:57
Did www.datahub.csail.mit.edu ever work? I'm fine with only supporting the plain domain name.

**Comment by RogerTangos** [comment] 2016-04-07 15:05
It didn't, and this is a really old issue. I'm fine to close it.

**Comment by justinanderson** [comment] 2016-04-07 15:16
Closing as works as intended. You can only get to CSAIL's DataHub instance via datahub.csail.mit.edu and datahub.mit.edu.

**Closed by justinanderson** 2016-04-07 15:16 UTC
